name: Enhancement proposal
description: Describe the enhancement you'd like to see
title: "Short title loaded with keywords"
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to give feedback on this software!

  - type: checkboxes
    attributes:
      label: Contributing guidelines
      description: |
        Please kindly follow this project's
        [Contributing Guidelines](https://github.com/kernc/backtesting.py/blob/master/CONTRIBUTING.md).
        The guidelines contain short technical notes on how to best contribute to this project.
      options:
        - label: |
            I agree to follow this project's
            [Contributing Guidelines](https://github.com/kernc/backtesting.py/blob/master/CONTRIBUTING.md)
            which, I understand, contain short technical notes on how to best contribute to this project.
          required: true

  - type: checkboxes
    attributes:
      label: Own due diligence
      options:
        - label: |
            I verify my due dilligence—I have went through the **tutorials** and the **API docs** and
            have used the **search** on **Issues** and GitHub **Disucussions**, as well all Google,
            with all the relevant search keywords.
          required: true

  - type: textarea
    id: expected
    validations:
      required: true
    attributes:
      label: Enhancement description
      description: What would you want to see in the software that doesn't appear to be presently included?
      placeholder: I absolutely love your software, but I'm missing a way to ...

  - type: textarea
    id: code
    validations:
      required: false
    attributes:
      label: Code sample
      description: Code snippet relevant to the new feature
      render: python

  - type: textarea
    id: steps
    validations:
      required: false
    attributes:
      label: Additional info, images
      description: |
        Extra information you think might be helpful or interesting.
