blank_issues_enabled: true
contact_links:
  - name: Reference documentation
    url: https://kernc.github.io/backtesting.py/doc/backtesting/
    about: Please confirm you've checked here first.
  - name: FAQ
    url: https://github.com/kernc/backtesting.py/issues?q=label%3Aquestion%20
    about: Frequently asked questions. Use search with potential keywords.
  - name: Discussion forum
    url: https://github.com/kernc/backtesting.py/discussions
    about: Other discussions. Make sure you've seen this too.
